config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  

  root "welcome#index"
  resources :workouts
  resources :gyms

  get 'welcome/', to: 'welcome#index' #http method to get
  get '/auth/:provider/callback', :to => 'omniauth#create'

  get '/get_fitbit_data/:id', :to => 'workouts#fitbit'

end

app/models/gym.rb
class Gym < ActiveRecord::Base
	has_many :workouts 
	has_many :memberships
	has_many :users, :through => :memberships

  validates :name, :workout_url, presence: true

  has_many :default_for_users, -> { default }, :class_name => 'Membership'
  
  def find_default (gym)
    Membership.find_by(gym_id: gym).default
  end

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
before_filter :authenticate_user!	
	def index
		@gyms = current_user.gyms
	end

	def new
    @gym = current_user.gyms.new
	end

  def create
    membership_default = params["gym"]["memberships"][:default]
    @gym = Gym.find_or_create_by(name:gym_params[:name], workout_url:gym_params[:workout_url])
    @membership = current_user.memberships.build(user_id: current_user.id, gym_id: @gym.id, default: membership_default == '1')

    if @membership.save
      if @gym.save
        flash[:notice] = "Gym created."
        redirect_to gym_path(@gym)
      else
        flash.now[:error] = @gym.errors.messages.first.join(" ")
        render 'new'
      end
    else
      flash.now[:alert] = @membership.errors[:alert].join(" ")
      render 'new'
    end    
  end

	def show
		@gym = current_user.gyms.find(params[:id])
    @workouts = current_user.workouts.where(gym: @gym)
	end

	def edit
		@gym = current_user.gyms.find(params[:id])
	end

	def update
    membership_default = params["gym"]["memberships"][:default]
    @gym = current_user.gyms.find_or_create_by(params[:id])
		if @gym.update(gym_params)
      @membership = Membership.find_or_create_by(gym_id: @gym.id, user_id: current_user.id)
      if @membership.update(default: membership_default == '1')
        flash[:notice] = "Gym updated."
        redirect_to gym_path(@gym)
      else
        flash.now[:alert] = @membership.errors[:alert].join(" ")
        render 'edit'
      end
    else
      flash.now[:error] = @gym.errors.messages.first.join(" ")
      render 'edit'
    end
	end

	def destroy
    # @gym = Gym.find(params[:id])
    @gym = current_user.gyms.find(params[:id])
    if @gym.destroy
      flash[:notice] = "Gym for #{@current_user.name} was deleted."
    else
      flash.now[:error] = @gym.errors.messages.first.join(" ")
    end
    redirect_to gyms_path
	end

  private

  def gym_params
    params.require(:gym).permit(:name, :workout_url)
  end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= form_for @gym, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="form-group">
        <%= f.label :name, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control " %>
      </div>
    </div>
    <div class="form-group">
        <%= f.label :workout_url, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :workout_url, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">

      <%= f.fields_for :memberships do |memberships_form| %>

          <%= memberships_form.label :default,  :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= memberships_form.check_box :default, :class => "form-control" %>
          </div>

      <% end %>
    <div class="form-group">
  
     <div class="col-sm-4 col-sm-offset-2">
      <%= f.submit 'Submit', class: 'btn btn-lg button_grey' %>
      <%= link_to 'Cancel', gyms_path, class: 'btn btn-lg button_grey' %>
     </div>
    </div>
    
<% end %>

app/views/gyms/_newform.html.erb
<%= form_for @gym, url: {action: "create"}, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="form-group">
        <%= f.label :name, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control " %>
      </div>
    </div>
    <div class="form-group">
        <%= f.label :workout_url, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :workout_url, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">

      <%= f.fields_for :memberships do |memberships_form| %>

          <%= memberships_form.label :default,  :class => "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= memberships_form.check_box :default, :class => "form-control" %>
          </div>

      <% end %>
    <div class="form-group">
  
     <div class="col-sm-4 col-sm-offset-2">
      <%= f.submit 'Create', class: 'btn btn-lg button_grey' %>
      <%= link_to 'Cancel', gyms_path, class: 'btn btn-lg button_grey' %>
     </div>
    </div>
    
<% end %>

app/views/gyms/edit.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1" style="text-align:center;">
      <h1 class="page_title"> Edit Gym for <%= @gym.name %> </h1>
  </div>
</div>

<div class="row" style="margin-top:20px;">
  <div class="col-md-10 col-md-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/gyms/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page_title"> Gyms </h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="row">
      <table class="table table-hover view_workouts">
        <tr>
          <td class="table_title" style="text-align:center; border-top: none !important;"> Gym Name </td>
          <td class="table_title" style="text-align:left; border-top: none !important;"> Link </td> 
          <td class="table_title" style="text-align:left; border-top: none !important;"> Default </td>
          <td class="table_title" style="text-align:center; border-top: none !important;"> </td>
        </tr>
        <% @gyms.each do |gym| %>
          <tr>
            <td style="text-align:center;">
              <%= link_to gym.name, gym_path(gym) %>
            </td>
            <td> 
               <%= link_to gym.workout_url, gym.workout_url %>
            </td>
            <td>
                <%= gym.find_default(gym).to_s.capitalize %>
            </td>
            <td style="text-align:center;">
              <%= link_to "X", gym_path(gym), method: 'delete' %>
            </td>
          </tr>
        <% end %>
      </table>
      <div class="row">
        <div class="col-xs-10">
          <%= link_to "Add New Gym", new_gym_path, :class =>"btn btn-md button_grey" %>
        </div>
      </div>   
    </div>
  </div>
</div>

app/views/gyms/new.html.erb
<div class="row">
    <div class="col-md-12">
      <h1 class="page_title">New Gym</h1>
    </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/gyms/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1" style="text-align:center;">
    <h1 class="page_title"> Recorded Workouts @ <%= @gym.name %> for <%= current_user.first_name %> </h1>
  </div>
</div>

<div class="row">
  <table class="table table-hover view_workouts">
    <tr>
      <td class="table_title" style="text-align:left; border-top: none !important;"> Date </td>
      <td class="table_title" style="text-align:center; border-top: none !important;"> Description </td> 
      <td class="table_title" style="text-align:center; border-top: none !important;"> Lift Type </td>
      <td class="table_title" style="text-align:center; border-top: none !important;"> Workout Result </td>
      <td class="table_title" style="text-align:center; border-top: none !important;"> </td>
    </tr>
    <% @workouts.each do |workout| %>
      <tr>
        <td>
          <%= link_to workout.workout_datetime.to_date.to_formatted_s(:long_ordinal), workout %>
          (<%= time_ago_in_words(workout.workout_datetime) %> ago)
        </td>
        <td> 
           <%= truncate(workout.description, length: 40, separator: ' ', omission: '') {link_to "...", workout} %>
        </td>
        <td style="text-align:center;">
          <%= workout.lift_type %>
        </td>
        <td style="text-align:center;">
          <%= workout.result %>
        </td>
        <td style="text-align:center;">
          <%= link_to "X", workout_path(workout), method: 'delete' %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="row">
    <div class="col-xs-10">
      <%= link_to "Edit Gym", edit_gym_path(id: @gym), :class=>"btn btn-sm button_grey" %>
<%= link_to "Delete Gym", gym_path(id: @gym), method: 'delete', :class=>"btn btn-sm button_grey" %>
    </div>
  </div>
</div>