config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  

  root "welcome#index"
  resources :workouts
  resources :gyms

  get 'welcome/', to: 'welcome#index' #http method to get
  get '/auth/:provider/callback', :to => 'omniauth#create'

  get '/get_fitbit_data/:id', :to => 'workouts#fitbit'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
  <body class="<%= content_for :body_class %> <%= controller_name %> <%= action_name %>">
    <div class="container" style="padding-left: 0; padding-right: 0;">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="font-weight: bolder;" href=<%= root_path %>>WOD Tracker</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in? %>
            <li><%= link_to "Log Workout", new_workout_path %></li>
            <li><%= link_to "View Workouts", workouts_path(id: "all") %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gyms <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "View", gyms_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Add", new_gym_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit User", edit_user_registration_path %></li>
                <li><%= link_to "Authenticate Fitbit", root_path + "auth/fitbit_oauth2" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign out as #{current_user.email}", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
      <%= render partial: "shared/flash_messages", flash: flash %>
    </div>
  <div class = 'container main_content'>
    <%= yield %>
  </div>
</body>
</html>